controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
App\Controller\StimulusAction:
    path: /stimulus
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: App/Controller/StimulusAction.html.twig